//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsageRecord
    {
        public int ID { get; set; }
        public string CurrentMileage { get; set; }
        public string TankLevel { get; set; }
        public int VehicleID { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
    }
}
