//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleOperator
    {
        public int ID { get; set; }
        public string OperatorNum { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> LicenseIssueDate { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public string Section { get; set; }
        public string JobTitle { get; set; }
        public string Location { get; set; }
        public Nullable<bool> OperatorStatus { get; set; }
        public Nullable<int> OperatorLicenseCode { get; set; }
        public string OperatorQualifications { get; set; }
        public string Comments { get; set; }
    }
}
