//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehiclePhoto
    {
        public int ID { get; set; }
        public byte[] VehiclePictures { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string PhotoFileName { get; set; }
    }
}
