//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleAccident
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfIncident { get; set; }
        public string TimeOfIncident { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string OperatorType { get; set; }
        public string LocationOfIncident { get; set; }
        public string ExactLocationOfIncident { get; set; }
        public string IncidentStatement { get; set; }
        public Nullable<int> DispatchID { get; set; }
    }
}
