//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeeklyDispatchLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string PreviousWeekMileage { get; set; }
        public string CurrentWeekMileage { get; set; }
        public string PreviousWeekFuelLevel { get; set; }
        public string CurrentWeekFuelLevel { get; set; }
    }
}
