//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeeklyInspection
    {
        public int ID { get; set; }
        public Nullable<bool> TiresCondition { get; set; }
        public Nullable<bool> TirePressure { get; set; }
        public Nullable<bool> TireSpare { get; set; }
        public Nullable<bool> HeadLights { get; set; }
        public Nullable<bool> LightsTail { get; set; }
        public Nullable<bool> LightsBrake { get; set; }
        public Nullable<bool> LightsTurnSignal { get; set; }
        public Nullable<bool> LightsBackup { get; set; }
        public Nullable<bool> LightsEmergencyFlasher { get; set; }
        public Nullable<bool> LightLicensePlate { get; set; }
        public Nullable<bool> LightFog { get; set; }
        public Nullable<bool> WindowShield { get; set; }
        public Nullable<bool> WindowRear { get; set; }
        public Nullable<bool> WindowDoor { get; set; }
        public Nullable<bool> WindowControl { get; set; }
        public Nullable<bool> WindowWipers { get; set; }
        public Nullable<bool> Mirrors { get; set; }
        public Nullable<bool> Brakes { get; set; }
        public Nullable<bool> EmergencyBrake { get; set; }
        public Nullable<bool> InteriorHorn { get; set; }
        public Nullable<bool> EmergencyEquipment { get; set; }
        public bool ACandHeater { get; set; }
        public Nullable<bool> Seatbelts { get; set; }
        public Nullable<bool> PlateandLicense { get; set; }
        public Nullable<bool> InstallationAccess { get; set; }
        public Nullable<bool> Registration { get; set; }
        public Nullable<bool> EmergencyContact { get; set; }
    }
}
