//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VASR_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewOperatorVehicleUsage
    {
        public string FullName { get; set; }
        public Nullable<System.DateTime> CheckoutTime { get; set; }
        public string EndMileage { get; set; }
        public string StartMileage { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string AdminNumber { get; set; }
        public string Model { get; set; }
        public int ID { get; set; }
        public string PlateNumber { get; set; }
    }
}
